### ISSUE TITLE
DllRegisterServe dll Com  interface !

### ISSUE THREAD

**Issue by Arsiprog** [MuaazH/ZKTeco_PULLSDK_Wrapper#9]
Can I use your DLL files as com interfaces for interaction in other programs? I tried to register your libraries via regsvr32 but I always get the DllRegisterServer error. I also tried to register libzkfp.dll and libzkfpcsharp.dll but without success, even though they are in the C folder: \Windows\SysWOW64

**Comment by Arsiprog** [comment]
Or can I use native api?

**Comment by MuaazH** [comment]
Why would you register anything?

You just place the dlls in path where your programs can find them. that would be:
1. in C:\Windows\System32 for system wide usage, since they are all x86. 
 Or
2. in the same folders as your executables, to avoid filling System32 with more rubbish

All dlls in "lib" are native, but the dll from "release" is not native, since it's source is in C#
To use native api, you have to read the C# code and understand how it works

**Comment by Arsiprog** [comment]
You didn’t understand me, for example I used zkemkeeper.dll
![Screenshot_10](https://github.com/MuaazH/ZKTeco_PULLSDK_Wrapper/assets/45854657/fb374cdc-eb77-45fb-a08e-ba0491f4b12a)

**Comment by Arsiprog** [comment]
This is 1C language

**Comment by Arsiprog** [comment]
I'll show you an example of how people make dlls for 1C

https://habr.com/ru/articles/666718/

to make it clearer for you

**Comment by Arsiprog** [comment]
Using zkemkeeper.dll I was able to integrate getting users, creating users, generating a report!

**Comment by Arsiprog** [comment]
Now I want to register my fingers!

**Comment by MuaazH** [comment]
> You didn’t understand me, for example I used zkemkeeper.dll ![Screenshot_10](https://private-user-images.githubusercontent.com/45854657/346293557-fb374cdc-eb77-45fb-a08e-ba0491f4b12a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTQ5OTQsIm5iZiI6MTcyMDI5NDY5NCwicGF0aCI6Ii80NTg1NDY1Ny8zNDYyOTM1NTctZmIzNzRjZGMtZWI3Ny00NWZiLWEwOGUtYmEwNDkxZjRiMTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDE5MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmODUzZGU5NTljYTNiOTUyYzkwMWRlMWM5Mzc0ZjY5OWFlNWFkNmFiZmUxMzkyM2VmMTNkZTU2NTUzMTVhNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BOd8mmR8p9fCNQCM3Z0q7JV2KKYyMwirUBgj0z5Mf7c)

No, I did understand you. So I ask, why would I make this wrapper into a ComObject that has to be registered instead of a simple library that can be included with any project?
Your answer is: "because that's the only way I know how to call it from 1C"

> This is 1C language

1C is something very specific, 1C:Enterprise platform is not supported by this repository.



> I'll show you an example of how people make dlls for 1C
> 
> https://habr.com/ru/articles/666718/
> 
> to make it clearer for you

Why would you assume I speak русский?



> Using zkemkeeper.dll I was able to integrate getting users, creating users, generating a report!

What kind of device do you have? is it an access control panel?





> Now I want to register my fingers!

The example is in [README.MD, but make sure you have the right setup first, a fingerprint reader and an access-control panel.](https://github.com/MuaazH/ZKTeco_PULLSDK_Wrapper?tab=readme-ov-file#how-to-use-zkfinger)

**Comment by Arsiprog** [comment]
Here 

![Изображение WhatsApp 2024-07-06 в 23 06 20_eec26dd2](https://github.com/MuaazH/ZKTeco_PULLSDK_Wrapper/assets/45854657/a6eeec04-105c-45c8-be7d-c8f23452f479)
![Изображение WhatsApp 2024-07-06 в 23 06 20_064e310e](https://github.com/MuaazH/ZKTeco_PULLSDK_Wrapper/assets/45854657/6401afc3-b823-4364-9b4f-64f06d2518d7)

**Comment by Arsiprog** [comment]
maybe you can do something like AddIn.libzkfp Native API ?

**Comment by MuaazH** [comment]
That device is not an access-control panel, The main library will not work with it.
The fingerprint device howerver is supported, but it only has C# API, but they are calling native dlls that come with its driver software.



> maybe you can do something like AddIn.libzkfp Native API ?

I have no plans of working on native apis to support any ZKTeco device at the moment.

**Comment by Arsiprog** [comment]
ok
